# Generated by Django 4.2 on 2024-04-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='count'),
        ),
    ]
