# Generated by Django 4.2 on 2024-05-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.IntegerField(default=0, verbose_name='مالیات'),
        ),
        migrations.AddField(
            model_name='order',
            name='transport',
            field=models.IntegerField(default=0, verbose_name='حمل و نقل'),
        ),
    ]
