# Generated by Django 4.2 on 2024-05-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0003_order_discount_orderitem_discount_alter_order_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='payment_amount_for_once',
            field=models.IntegerField(default=0, verbose_name='مبلغ پرداختی هر محصول'),
        ),
    ]
