# Generated by Django 4.2 on 2024-04-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('fullname', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('response_time', models.DateTimeField(auto_now=True)),
                ('is_read_by_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'لیست تماس ها',
                'db_table': 'contact',
            },
        ),
    ]
