# Generated by Django 4.2 on 2024-04-13 00:21

from django.db import migrations
import django_extensions.db.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0003_rename_crated_time_article_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=model_utils.fields.StatusField(choices=[('draft', 'draft'), ('published', 'published'), ('hidden', 'hidden'), ('archived', 'archived'), ('deleted', 'deleted')], default='draft', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, populate_from='title'),
        ),
        migrations.AlterIndexTogether(
            name='article',
            index_together={('slug', 'created_time')},
        ),
    ]
