# Generated by Django 4.2 on 2024-04-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
