# Generated by Django 4.2 on 2024-04-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_slider_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='utl_title',
            new_name='url_title',
        ),
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
