# Generated by Django 4.2 on 2024-04-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_rename_utl_title_slider_url_title_slider_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=150)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='banners/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
