# Generated by Django 4.2 on 2024-04-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_code',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
