# Generated by Django 4.2 on 2024-04-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_user_active_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='abut_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
